apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brain-stroke-prediction
  namespace: default
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 25
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brain-stroke-prediction